winrt::build!(
    dependencies
        os
    types
        windows::ai::machine_learning::*
        windows::ai::machine_learning::preview::*
        windows::application_model::*
        windows::application_model::activation::*
        windows::application_model::app_extensions::*
        windows::application_model::app_service::*
        windows::application_model::appointments::*
        windows::application_model::appointments::appointments_provider::*
        windows::application_model::appointments::data_provider::*
        windows::application_model::background::*
        windows::application_model::calls::*
        windows::application_model::calls::background::*
        windows::application_model::calls::provider::*
        windows::application_model::chat::*
        windows::application_model::communication_blocking::*
        windows::application_model::contacts::*
        windows::application_model::contacts::data_provider::*
        windows::application_model::contacts::provider::*
        windows::application_model::conversational_agent::*
        windows::application_model::core::*
        windows::application_model::data_transfer::*
        windows::application_model::data_transfer::drag_drop::*
        windows::application_model::data_transfer::drag_drop::core::*
        windows::application_model::data_transfer::share_target::*
        windows::application_model::email::*
        windows::application_model::email::data_provider::*
        windows::application_model::extended_execution::*
        windows::application_model::extended_execution::foreground::*
        windows::application_model::lock_screen::*
        windows::application_model::payments::*
        windows::application_model::payments::provider::*
        windows::application_model::preview::holographic::*
        windows::application_model::preview::ink_workspace::*
        windows::application_model::preview::notes::*
        windows::application_model::resources::*
        windows::application_model::resources::core::*
        windows::application_model::resources::management::*
        windows::application_model::search::*
        windows::application_model::search::core::*
        windows::application_model::social_info::*
        windows::application_model::social_info::provider::*
        windows::application_model::store::*
        windows::application_model::store::license_management::*
        windows::application_model::store::preview::*
        windows::application_model::store::preview::install_control::*
        windows::application_model::user_activities::*
        windows::application_model::user_activities::core::*
        windows::application_model::user_data_accounts::*
        windows::application_model::user_data_accounts::provider::*
        windows::application_model::user_data_accounts::system_access::*
        windows::application_model::user_data_tasks::*
        windows::application_model::user_data_tasks::data_provider::*
        windows::application_model::voice_commands::*
        windows::application_model::wallet::*
        windows::application_model::wallet::system::*
        windows::data::html::*
        windows::data::json::*
        windows::data::pdf::*
        windows::data::text::*
        windows::data::xml::dom::*
        windows::data::xml::xsl::*
        windows::devices::*
        windows::devices::adc::*
        windows::devices::adc::provider::*
        windows::devices::all_joyn::*
        windows::devices::background::*
        windows::devices::bluetooth::*
        windows::devices::bluetooth::advertisement::*
        windows::devices::bluetooth::background::*
        windows::devices::bluetooth::generic_attribute_profile::*
        windows::devices::bluetooth::rfcomm::*
        windows::devices::custom::*
        windows::devices::display::*
        windows::devices::display::core::*
        windows::devices::enumeration::*
        windows::devices::enumeration::pnp::*
        windows::devices::geolocation::*
        windows::devices::geolocation::geofencing::*
        windows::devices::gpio::*
        windows::devices::gpio::provider::*
        windows::devices::haptics::*
        windows::devices::human_interface_device::*
        windows::devices::i2c::*
        windows::devices::i2c::provider::*
        windows::devices::input::*
        windows::devices::input::preview::*
        windows::devices::lights::*
        windows::devices::lights::effects::*
        windows::devices::midi::*
        windows::devices::perception::*
        windows::devices::perception::provider::*
        windows::devices::point_of_service::*
        windows::devices::point_of_service::provider::*
        windows::devices::portable::*
        windows::devices::power::*
        windows::devices::printers::*
        windows::devices::printers::extensions::*
        windows::devices::pwm::*
        windows::devices::pwm::provider::*
        windows::devices::radios::*
        windows::devices::scanners::*
        windows::devices::sensors::*
        windows::devices::sensors::custom::*
        windows::devices::serial_communication::*
        windows::devices::smart_cards::*
        windows::devices::sms::*
        windows::devices::spi::*
        windows::devices::spi::provider::*
        windows::devices::usb::*
        windows::devices::wi_fi::*
        windows::devices::wi_fi_direct::*
        windows::devices::wi_fi_direct::services::*
        windows::foundation::*
        windows::foundation::collections::*
        windows::foundation::diagnostics::*
        windows::foundation::metadata::*
        windows::foundation::numerics::*
        windows::gaming::input::*
        windows::gaming::input::custom::*
        windows::gaming::input::force_feedback::*
        windows::gaming::input::preview::*
        windows::gaming::preview::games_enumeration::*
        windows::gaming::ui::*
        windows::gaming::xbox_live::storage::*
        windows::globalization::*
        windows::globalization::collation::*
        windows::globalization::date_time_formatting::*
        windows::globalization::fonts::*
        windows::globalization::number_formatting::*
        windows::globalization::phone_number_formatting::*
        windows::graphics::*
        windows::graphics::capture::*
        windows::graphics::direct_x::*
        windows::graphics::direct_x::direct3d11::*
        windows::graphics::display::*
        windows::graphics::display::core::*
        windows::graphics::effects::*
        windows::graphics::holographic::*
        windows::graphics::imaging::*
        windows::graphics::printing::*
        windows::graphics::printing::option_details::*
        windows::graphics::printing::print_ticket::*
        windows::graphics::printing::workflow::*
        windows::graphics::printing3d::*
        windows::management::*
        windows::management::core::*
        windows::management::deployment::*
        windows::management::deployment::preview::*
        windows::management::policies::*
        windows::management::update::*
        windows::management::workplace::*
        windows::media::*
        windows::media::app_broadcasting::*
        windows::media::app_recording::*
        windows::media::audio::*
        windows::media::capture::*
        windows::media::capture::core::*
        windows::media::capture::frames::*
        windows::media::casting::*
        windows::media::closed_captioning::*
        windows::media::content_restrictions::*
        windows::media::control::*
        windows::media::core::*
        windows::media::core::preview::*
        windows::media::devices::*
        windows::media::devices::core::*
        windows::media::dial_protocol::*
        windows::media::editing::*
        windows::media::effects::*
        windows::media::face_analysis::*
        windows::media::import::*
        windows::media::media_properties::*
        windows::media::miracast::*
        windows::media::ocr::*
        windows::media::play_to::*
        windows::media::playback::*
        windows::media::playlists::*
        windows::media::protection::*
        windows::media::protection::play_ready::*
        windows::media::render::*
        windows::media::speech_recognition::*
        windows::media::speech_synthesis::*
        windows::media::streaming::adaptive::*
        windows::media::transcoding::*
        windows::networking::*
        windows::networking::background_transfer::*
        windows::networking::connectivity::*
        windows::networking::network_operators::*
        windows::networking::proximity::*
        windows::networking::push_notifications::*
        windows::networking::service_discovery::dnssd::*
        windows::networking::sockets::*
        windows::networking::vpn::*
        windows::networking::xbox_live::*
        windows::perception::*
        windows::perception::automation::core::*
        windows::perception::people::*
        windows::perception::spatial::*
        windows::perception::spatial::preview::*
        windows::perception::spatial::surfaces::*
        windows::security::authentication::identity::*
        windows::security::authentication::identity::core::*
        windows::security::authentication::identity::provider::*
        windows::security::authentication::online_id::*
        windows::security::authentication::web::*
        windows::security::authentication::web::core::*
        windows::security::authentication::web::provider::*
        windows::security::authorization::app_capability_access::*
        windows::security::credentials::*
        windows::security::credentials::ui::*
        windows::security::cryptography::*
        windows::security::cryptography::certificates::*
        windows::security::cryptography::core::*
        windows::security::cryptography::data_protection::*
        windows::security::data_protection::*
        windows::security::enterprise_data::*
        windows::security::exchange_active_sync_provisioning::*
        windows::services::cortana::*
        windows::services::maps::*
        windows::services::maps::guidance::*
        windows::services::maps::local_search::*
        windows::services::maps::offline_maps::*
        windows::services::store::*
        windows::services::targeted_content::*
        windows::storage::*
        windows::storage::access_cache::*
        windows::storage::bulk_access::*
        windows::storage::compression::*
        windows::storage::file_properties::*
        windows::storage::pickers::*
        windows::storage::pickers::provider::*
        windows::storage::provider::*
        windows::storage::search::*
        windows::storage::streams::*
        windows::system::*
        windows::system::diagnostics::*
        windows::system::diagnostics::device_portal::*
        windows::system::diagnostics::telemetry::*
        windows::system::diagnostics::trace_reporting::*
        windows::system::display::*
        windows::system::inventory::*
        windows::system::power::*
        windows::system::power::diagnostics::*
        windows::system::preview::*
        windows::system::profile::*
        windows::system::profile::system_manufacturers::*
        windows::system::remote_desktop::*
        windows::system::remote_systems::*
        windows::system::threading::*
        windows::system::threading::core::*
        windows::system::update::*
        windows::system::user_profile::*
        windows::ui::*
        windows::ui::accessibility::*
        windows::ui::application_settings::*
        windows::ui::composition::*
        windows::ui::composition::core::*
        windows::ui::composition::desktop::*
        windows::ui::composition::diagnostics::*
        windows::ui::composition::effects::*
        windows::ui::composition::interactions::*
        windows::ui::composition::scenes::*
        windows::ui::core::*
        windows::ui::core::animation_metrics::*
        windows::ui::core::preview::*
        windows::ui::input::*
        windows::ui::input::core::*
        windows::ui::input::inking::*
        windows::ui::input::inking::analysis::*
        windows::ui::input::inking::core::*
        windows::ui::input::inking::preview::*
        windows::ui::input::preview::*
        windows::ui::input::preview::injection::*
        windows::ui::input::spatial::*
        windows::ui::notifications::*
        windows::ui::notifications::management::*
        windows::ui::popups::*
        windows::ui::shell::*
        windows::ui::start_screen::*
        windows::ui::text::*
        windows::ui::text::core::*
        windows::ui::view_management::*
        windows::ui::view_management::core::*
        windows::ui::web_ui::*
        windows::ui::window_management::*
        windows::ui::window_management::preview::*
        windows::ui::xaml::*
        windows::ui::xaml::automation::*
        windows::ui::xaml::automation::peers::*
        windows::ui::xaml::automation::provider::*
        windows::ui::xaml::automation::text::*
        windows::ui::xaml::controls::*
        windows::ui::xaml::controls::maps::*
        windows::ui::xaml::controls::primitives::*
        windows::ui::xaml::core::direct::*
        windows::ui::xaml::data::*
        windows::ui::xaml::documents::*
        windows::ui::xaml::hosting::*
        windows::ui::xaml::input::*
        windows::ui::xaml::interop::*
        windows::ui::xaml::markup::*
        windows::ui::xaml::media::*
        windows::ui::xaml::media::animation::*
        windows::ui::xaml::media::imaging::*
        windows::ui::xaml::media::media3d::*
        windows::ui::xaml::navigation::*
        windows::ui::xaml::printing::*
        windows::ui::xaml::resources::*
        windows::ui::xaml::shapes::*
        windows::web::*
        windows::web::atom_pub::*
        windows::web::http::*
        windows::web::http::diagnostics::*
        windows::web::http::filters::*
        windows::web::http::headers::*
        windows::web::syndication::*
        windows::web::ui::*
        windows::web::ui::interop::*
);

fn main() {
    build();
}
